---
title: "Sociodemografía"
---

## Sociodemografía

## Objetivo

El curso pretende dar las herramientas para que el estudiantado pueda analizar los fenómenos sociales desde una perspectiva demográfica. Quienes tomen este curso, al final deberán ser capaces de identificar los fenómenos demográficos, sus fuentes y los principales indicadores que informan sobre los mismos. Del mismo modo, podrá describir las distintas corrientes de pensamiento demográfico, para el caso de América Latina y México. También se pretende que les estudiantes sean capaces aplicar los instrumentos y técnicas de análisis que permitan el estudio y la caracterización de los fenómenos demográficos y poblacionales en general.

## Tareas

Todas las tareas se entregan por Google Classroom: las profe te darán el código de la clase

## Biblio

Por aquí algunas lecturas... [drive](https://drive.google.com/drive/folders/1JThhuJH1uPjJGTbRFQMVjh86N98As1fD?usp=share_link)

## Sitios de interés

### Diccionarios

-   [Demopaedia](http://www.demopaedia.org/)

-   [Diccionario multilingüe](http://www.demopaedia.org/tools/?lang=en)

### Sitios nacionales

-   [Instituto Nacional de Estadística y Geografía (INEGI)](https://www.inegi.org.mx/)

-   [Datos Abiertos de México - CONAPO - Proyecciones](https://datos.gob.mx/busca/dataset/proyecciones-de-la-poblacion-de-mexico-y-de-las-entidades-federativas-2016-2050)

### Fuentes temáticas

#### Mortalidad

-   [Human Mortality Database](http://www.mortality.org/)

-   [Latin American Human Mortality Database](http://www.lamortalidad.org/)

-   [Human Life-Table Database](https://www.lifetable.de/)

#### Fecundidad

-   [Human Fertility Database](http://www.humanfertility.org/)

#### Migración (México)

-   [Global Migration Database](https://www.un.org/development/desa/pd/data/global-migration-database)

-   <http://www.omi.gob.mx/es/OMI/Encuestas>
